<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/07/26 15:35:56
sfConfig::add(array(
  'app_sf_admin_dash_web_dir' => '/sfAdminDashPlugin',
  'app_sf_admin_dash_image_dir' => '/sfAdminDashPlugin/images/icons/',
  'app_sf_admin_dash_default_image' => 'config.png',
  'app_sf_admin_dash_resize_mode' => 'thumbnail',
  'app_sf_admin_dash_logout' => true,
  'app_sf_admin_dash_site' => 'My Site',
  'app_sf_admin_dash_include_path' => true,
  'app_sf_admin_dash_include_jquery_no_conflict' => false,
  'app_sf_admin_dash_login_route' => '@sf_guard_signin',
  'app_sf_admin_dash_logout_route' => '@sf_guard_signout',
  'app_sf_captchagd_image_width' => 90,
  'app_sf_captchagd_image_height' => 34,
  'app_sf_captchagd_chars' => '123456789',
  'app_sf_captchagd_length' => 4,
  'app_sf_captchagd_font_size' => 18,
  'app_sf_captchagd_force_new_captcha' => true,
  'app_sf_captchagd_font_color' => array (
  0 => '252525',
  1 => '8b8787',
  2 => '550707',
  3 => '3526E6',
  4 => '88531E',
),
  'app_sf_captchagd_fonts' => array (
  0 => 'akbar/akbar.ttf',
  1 => 'brushcut/BRUSHCUT.TTF',
  2 => 'molten/molten.ttf',
  3 => 'planet_benson/Planetbe.ttf',
  4 => 'whoobub/WHOOBUB_.TTF',
),
  'app_sf_captchagd_background_color' => 'DDDDDD',
  'app_sf_captchagd_border_color' => 0,
));
