<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/07/28 16:54:45
sfConfig::add(array(
  'mod_information_center_enabled' => true,
  'mod_information_center_view_class' => 'sfPHP',
));
