<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/08/04 12:35:40
sfConfig::add(array(
  'mod_commodity_list_enabled' => true,
  'mod_commodity_list_view_class' => 'sfPHP',
));
