<?php
// auto-generated by sfViewConfigHandler
// date: 2016/08/04 12:35:53
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('/css/3rd/font-awesome/css/font-awesome.min.css', '', array ());
  $response->addStylesheet('/css/apps/frontend/head.css', '', array ());
  $response->addStylesheet('/css/apps/frontend/app.css', '', array ());
  $response->addStylesheet('/css/apps/frontend/pattern/module.css', '', array ());
  $response->addJavascript('/js/jquery-1.7.2.min.js', '', array ());
  $response->addJavascript('/js/jquery-1.8.3.min.js', '', array ());
  $response->addJavascript('jquery.tools.min.js', '', array ());
  $response->addJavascript('scrolltopcontrol.js', '', array ());
  $response->addJavascript('/js/head.js', '', array ());


