<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/07/27 17:42:25
sfConfig::add(array(
  'mod_commodity_list_enabled' => true,
  'mod_commodity_list_view_class' => 'sfPHP',
));
