generator:
  class: sfPropelGenerator
  param:
    model_class:           News
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              News
    plural:                Newss
    route_prefix:          news
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        title: {label: 标题}
        body: {label: 正文内容}
        is_enable: {label: 状态, help: 勾选之后则可以正常访问，否则将不能访问该文章}
        created_at: {label: 添加日期}
        image: {label: 缩略图}
        summary: {label: 摘要}
        is_show_homepage: {label: 首页显示, help: 勾选之后在首页将高亮显示（缩略图，标题，摘要）}
      list:
        title: 非农新闻列表
        display: [id,_title,_is_enable,_created_at]
        sort: [id, desc]
      filter:
        display: [title,is_enable,is_show_homepage]
      form:
        display: [title,image,summary,body,is_enable,is_show_homepage]
      edit:
        title: 编辑非农新闻
      new:
        title: 新建非农新闻
