all:  
  stylesheets:    [/css/apps/admin/news/module.css]
  javascripts:    [/js/3rd/kindeditor/kindeditor-min.js,/js/3rd/kindeditor/lang/zh_CN.js,/js/3rd/datetimepicker/js/jquery-ui-timepicker-addon.js,/js/apps/admin/news/module.js]  