all:  
  stylesheets:    [/css/apps/admin/admin_user_profile/module.css]
  javascripts:    [/js/apps/admin/admin_user_profile/ZeroClipboard.js,/js/apps/admin/admin_user_profile/jquery.pstrength-min.1.2.js]  