generator:
  class: sfPropelGenerator
  param:
    model_class:           Regulation
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              Regulation
    plural:                Regulations
    route_prefix:          regulation
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        title: {label: 标题}
        regulation_category_id: {label: 类别}
        release_date: {label: 发布日期}
        body: {label: 正文内容}
        is_enable: {label: 状态, help: 勾选之后则可以正常访问，否则将不能访问该文章}
        created_at: {label: 添加日期}
        image: {label: 缩略图}
        page_view: {label: 浏览量}
        summary: {label: 摘要}
        seo_keywords: {label: 关键词}
        seo_description: {label: 描述}
      list:
        title: 规则制度列表
        display: [id,_regulation_category_id,_title,_is_enable,page_view,_release_date]
        sort: [id, desc]
      filter:
        display: [regulation_category_id,title,is_enable,release_date]
      form:
        display: [regulation_category_id,title,release_date,image,summary,body,page_view,is_enable]
      edit:
        title: 编辑规则
      new:
        title: 新建规则
