all:  
  stylesheets:    [/css/apps/admin/regulation/module.css]
  javascripts:    [/js/3rd/kindeditor/kindeditor-min.js,/js/3rd/kindeditor/lang/zh_CN.js,/js/3rd/laydate-v1.1/laydate/laydate.js,/js/apps/admin/regulation/module.js] 