<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/08/03 06:22:38

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=w_qingxi;host=localhost',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'persistent' => true,
  'name' => 'propel',
)),);
