<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/06/22 06:35:48

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=init;host=localhost',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'persistent' => true,
  'name' => 'propel',
)),);
